### ISSUE TITLE
Parameter in non-generic class that derives from a generic base class that implements a generic interface is incorrectly reported

### ISSUE THREAD

**Issue by bkoelman** [bkoelman/ResharperCodeContractNullability#13]
Created a new issue to track the bug submitted at https://github.com/bkoelman/ResharperCodeContractNullability/issues/5#issuecomment-169161211.

@starkcolin Thanks for reporting!

Minimal repro for [v1.0.3](https://github.com/bkoelman/ResharperCodeContractNullability/releases/tag/v1.0.3):

```csharp
    public interface I<T>
    {
        void Do([NotNull] T p);
    }

    public class B<T> : I<T>
    {
        public virtual void Do(T p)
        {
        }
    }

    public class D : B<string>
    {
        public override void Do(string p)
        {
        }
    }
```

The nullability analyzer incorrectly reports on the line of `D.Do`:
```
Parameter 'p' is missing nullability annotation.
```

**Comment by bkoelman** [comment]
The strange thing is: the nullability report goes away when renaming method `Do` to `M`.

Tracked this down to [a Roslyn API call](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/Symbols/TypeSymbol.cs,21984c887a839406) and created https://github.com/dotnet/roslyn/issues/7794.

**Comment by bkoelman** [comment]
@starkcolin Feel free to try out this fix in the prerelease version (see https://github.com/bkoelman/ResharperCodeContractNullability#trying-out-the-latest-build). 

If that works for you, I'll create a new release.

**Comment by starkcolin** [comment]
Happy to report that the issue appears to be resolved.  Thanks!

**Comment by bkoelman** [comment]
https://github.com/bkoelman/ResharperCodeContractNullability/releases/tag/v1.0.4
