### ISSUE TITLE
Ignore Equals methods

### ISSUE THREAD

**Issue by imanushin** [bkoelman/ResharperCodeContractNullability#26]
All overrides of object.Equals method have the following semantic: it can have null on input. ReSharper knows it and handle this case: it adds CanBeNull to argument implicitly.

I suggest to remove RNUL warning from such overrides:

```
public override bool Equals(object obj) //obj can be null, ReSharper knows this
{
    if (ReferenceEquals(null, obj)) return false;
    if (ReferenceEquals(this, obj)) return true;
    return obj is PortablePoint && Equals((PortablePoint)obj);
}
```

Absolutely the same with IEquality interface implementation: bool Equals(MyType ..), etc.

**Comment by bkoelman** [comment]
What makes you think that Resharper knows this? 
What Resharper version are you using?
