### ISSUE TITLE
Leaves a space behind when removing from function parameter

### ISSUE THREAD

**Issue by RedX2501** [bkoelman/ResharperCodeContractNullability#43]
**Version Used**: 2.0.2

**Steps to Reproduce**:

Have a function with the following signature:

```csharp
public void DoSomething(
   [CanBeNull] bool theParameter,
   bool someOtherParameter
  {
  }
```

**Expected Behavior**:

After applying the CNUL rule:

```csharp
public void DoSomething(
   bool? theParameter,
   bool someOtherParameter
  {
  }
```

**Actual Behavior**:

Notice the space left behind in front of the `bool`:
```csharp
public void DoSomething(
    bool? theParameter,
   bool someOtherParameter
  {
  }
```

**Comment by bkoelman** [comment]
Thanks for reporting, I understand this is quite annoying.

Unfortunately, the code formatter API in Visual Studio is very limited. There are no settings for whitespace handling around attributes, so I implemented that myself for the default case (which means all parameters on the same line). See [here](https://github.com/bkoelman/ResharperCodeContractNullability/blob/4a03ac44c11b3ee57fee23804424445034cabc67/src/CodeContractNullability/CodeContractNullability/Conversion/ResharperNullabilityAttributesRemover.cs#L155) for details. It is nearly impossible to get this right for the various styles used by developers, without relying on a formatter that 'understands' your style.

For formatting my own code, I'm using Resharper instead, which has overwhelming support for details like this. It can infer basic style settings from your codebase. Once configured properly, it only takes a single command to reformat all your code. Although Resharper is not free, their command-line runners are.
